name: eyedentify3d
channels:
  - conda-forge
dependencies:
  - python=3.11
  - biorbd=1.11.2
  - pip
  - pip:
    - numpy
    - scipy
    - matplotlib
    - pandas
    - pingouin
    - pytest
    - pytest-cov
    - codecov
    - black

